# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "distributed_mutex"
  s.version = "1.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Birkir A. Barkarson"]
  s.date = "2011-12-06"
  s.description = "Framework for using a distributed mutex along with an implementation of a mutex stored on a MySQL database."
  s.email = "birkirb@stoicviking.net"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/distributed_mutex.rb",
    "lib/global_mutex.rb",
    "lib/mutex_lock_release_failure.rb",
    "lib/mutex_lock_timeout.rb",
    "lib/mysql_mutex.rb",
    "rails/init.rb",
    "spec/config/database.stub",
    "spec/global_mutex_spec.rb",
    "spec/mysql_mutex_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/birkirb/distributed_mutex"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.12"
  s.summary = "API for using a unique mutex across all instances of your application."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_runtime_dependency(%q<mysql>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<mysql>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<mysql>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

